[package]
name = "web-consumer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cassini-client.workspace = true
cassini-types.workspace = true
futures-lite.workspace = true
neo4rs.workspace = true
polar.workspace = true
ractor.workspace = true
reqwest = { workspace = true, features = ["json"] }
ring.workspace = true
rkyv.workspace = true
rustls-webpki.workspace = true
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs", "ring", "std"] }
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true
web-agent-common.workspace = true
webpki-roots.workspace = true
