[package]
name = "web-consumer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
web-agent-common = { path = "../common" }
futures-lite = "2.6.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["std", "env-filter"] }
reqwest = { workspace = true, features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
ractor = { version = "0.15.8", features = ["async-trait"] }
serde_json = "1.0.145"
cassini-client = { workspace = true }
cassini-types  = { workspace = true }
utoipa = "5.4.0"
neo4rs = { workspace = true }
url = "2.5.7"
polar = { path = "../../lib" }
rkyv = { workspace = true }
# Fix a vulnerability in a transitive dependency.
ring = { version = "=0.17.14" }
rustls = { version = "0.23", default-features = false, features = [
    "aws-lc-rs",
    "ring",
    "std",
] }
rustls-webpki = { version = "0.103" }
webpki-roots = { workspace = true }
