apiVersion: v1
data:
  neo4j.conf: |2
        server.jvm.additional=-Dunsupported.dbms.udc.source=docker
    
        server.memory.heap.initial_size=2g
        server.memory.heap.max_size=6g
        # server.memory.pagecache.size=512M
    
        server.http.enabled=true
        server.https.enabled=false
        server.http.listen_address=0.0.0.0:7473
        server.http.advertised_address=graph-db-ws.local:443
    
        dbms.logs.http.enabled=true
        server.logs.debug.enabled=true
    
        #dbms.ssl.policy.https.enabled=false
        #dbms.ssl.policy.https.base_directory=certificates/https
        #dbms.ssl.policy.https.public_certificate = tls.crt
        #dbms.ssl.policy.https.private_key = tls.key
    
        server.bolt.enabled=true
        server.bolt.listen_address=0.0.0.0:7687
        server.bolt.advertised_address=graph-db-ws.local:443
    
        dbms.ssl.policy.bolt.enabled = false
        # dbms.ssl.policy.bolt.base_directory=certificates/bolt
        # dbms.ssl.policy.bolt.private_key = tls.key
        # dbms.ssl.policy.bolt.public_certificate = tls.crt
        # dbms.ssl.policy.bolt.client_auth=NONE
        # dbms.ssl.policy.bolt.trust_all=true
        # dbms.ssl.policy.bolt.trust_certificates=ca.crt
    
        # disable telemetry
        dbms.usage_report.enabled=false
    server.memory.pagecache.size=512M
    
    server.default_listen_address=0.0.0.0
    server.directories.logs=/logs
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: polar-db
