[package]
name = "jira-queries"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jira-schema = { path = "../schema" }
rkyv.workspace = true

[build-dependencies]
cynic-codegen = { version = "3.9.1", features = ["rkyv"] }
