[package]
name = "policy-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
git2.workspace = true
urlencoding.workspace = true

[dev-dependencies]
anyhow.workspace = true
proptest.workspace = true
tempfile.workspace = true
