[package]
name = "provenance-resolver"
version.workspace = true
edition.workspace = true

[dependencies]
ractor = { version = "0.15.10", features = ["async-trait"] }
tracing = "0.1.44"
cassini-client = { path = "../../cassini/client/" }
cassini-types = { path = "../../cassini/types" }
features = "0.10.0"
polar = { path = "../../lib/" }
oci-client = "0.15.0"
docker_credential = "1.3.2"
tokio = { version = "1.49.0", features = ["full"] }
rkyv = {workspace = true}
provenance-common = { path = "../provenance-common/" }
reqwest = { workspace = true, features = ["json"] }
serde ="1"
serde_json = "1.0.149"
cyclonedx-bom = "0.8.0"
