[package]
name = "provenance-resolver"
version.workspace = true
edition.workspace = true

[dependencies]
ractor = { version = "0.15.9", features = ["async-trait"] }
tracing = "0.1.41"
cassini-client = { path = "../../cassini/client/" }
features = "0.10.0"
polar = { path = "../../lib/" }
oci-client = "0.15.0"
docker_credential = "1.3.2"
tokio = { version = "1.48.0", features = ["full"] }
rkyv = {workspace = true}
provenance-common = { path = "../provenance-common/" }
reqwest = { workspace = true, features = ["json"]}
