# Polar (OSS)

# Copyright 2024 Carnegie Mellon University.

# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS
# TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
# OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
# WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.

# Licensed under a MIT-style license, please see license.txt or contact
# permission@sei.cmu.edu for full terms.

# [DISTRIBUTION STATEMENT A] This material has been approved for public release
# and unlimited distribution.  Please see Copyright notice for non-US
# Government use and distribution.

# This Software includes and/or makes use of Third-Party Software each subject
# to its own license.

# DM24-0470

[package]
name = "jira-consumer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
# Workspace crates
lapin = { workspace = true }
neo4rs = { workspace = true }
cassini-backoff = { workspace = true }

# Cassini internal crates
cassini-client = { path = "../../cassini/client" }
cassini-types  = { path = "../../cassini/types" }

# Other internal agents/libraries
polar = { path = "../../lib" }
jira_common = { path = "../common" }

# Third-party deps
tokio = { version = "1", features = ["full"] }
async-global-executor = "3.1.0"
futures-lite = "2.6.1"
serde_json = "1.0"
url = "2.5.7"
tracing = "0.1.41"
ractor = { version = "0.15.8", features = ["async-trait"] }

rkyv = { workspace = true, features = ["std", "alloc"] }
[[bin]]
name = "jira-consumer"
path = "src/entrypoint.rs"
