[package]
name = "provenance-linker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cassini-client.workspace = true
cassini-types.workspace = true
chrono.workspace = true
cyclonedx-bom.workspace = true
neo4rs.workspace = true
polar.workspace = true
provenance-common.workspace = true
ractor.workspace = true
reqwest = { workspace = true, features = ["json"] }
rkyv.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
