[package]
name = "provenance-linker"
version.workspace = true
edition.workspace = true
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.41"
ractor = { version = "0.15.8", features = ["async-trait"] }
rkyv = { workspace = true }
polar = { path = "../../lib" }
neo4rs = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
cyclonedx-bom = "0.8.0"
anyhow = "1.0.100"
provenance-common = { path = "../provenance-common/" }
cassini-client = { path = "../../cassini/client" }
cassini-types = { path = "../../cassini/types" }
