[package]
name = "web-agent-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
polar.workspace = true
ractor.workspace = true
rkyv.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-glog.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true
