# Polar (OSS)

# Copyright 2024 Carnegie Mellon University.

# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS
# TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
# OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
# WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.

# Licensed under a MIT-style license, please see license.txt or contact
# permission@sei.cmu.edu for full terms.

# [DISTRIBUTION STATEMENT A] This material has been approved for public release
# and unlimited distribution.  Please see Copyright notice for non-US
# Government use and distribution.

# This Software includes and/or makes use of Third-Party Software each subject
# to its own license.

# DM24-0470

services:
  neo4j:
    user: 7474:7474
    image: registry1.dso.mil/ironbank/opensource/neo4j/neo4j:5.26.2
    restart: never
    environment:
      - NEO4J_AUTH=neo4j/somepassword
    networks:
      - polar
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      # - ./neo4j-no-ssl.conf:/var/lib/neo4j/conf
      - ./neo4j_setup/imports:/var/lib/neo4j/import

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.11.0
    ports:
      - 4317:4317
      - 4318:4318
      - 5778:5778
      - 9411:9411
    networks:
      - polar
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  cassini:
    depends_on:
      - jaeger
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/cassini:386858fe
    networks:
      - polar
    ports:
      - 8080:8080
    environment:
      - BROKER_ADDR=localhost:8080
      - TLS_CA_CERT=/etc/ssl/ca_certificate.pem
      - TLS_SERVER_CERT_CHAIN=/etc/ssl/server_cassini_certificate.pem
      - TLS_SERVER_KEY=/etc/ssl/server_cassini_key.pem
    volumes:
      - ./certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ./certs/server/server_cassini_key.pem:/etc/ssl/server_cassini_key.pem:ro
      - ./certs/server/server_cassini_certificate.pem:/etc/ssl/server_cassini_certificate.pem:ro

  gitlab-observer:
    depends_on:
      - cassini
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-gitlab-observer:386858fe
    networks:
      - polar
    env_file: gitlab.env
    environment:
      - BROKER_ADDR=cassini:8080
      - CASSINI_SERVER_NAME=cassini
      - TLS_CA_CERT=/etc/ssl/ca_certificate.pem
      - TLS_CLIENT_CERT=/etc/ssl/tls.crt
      - TLS_CLIENT_KEY=/etc/ssl/tls.key
      - PROXY_CA_CERT=/etc/ssl/proxy_ca.pem
      - OBSERVER_BASE_INTERVAL=30
    volumes:
      - ./certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ./certs/client/client_cassini_key.pem:/etc/ssl/tls.key:ro
      - ./certs/client/client_cassini_certificate.pem:/etc/ssl/tls.crt:ro
      - ./certs/proxy_ca.pem:/etc/ssl/proxy_ca.pem:ro

  gitlab-consumer:
    depends_on:
      - cassini
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-gitlab-consumer:386858fe
    networks:
      - polar
    environment:
      - BROKER_ADDR=cassini:8080
      - CASSINI_SERVER_NAME=cassini
      - TLS_CA_CERT=/etc/ssl/ca_certificate.pem
      - TLS_CLIENT_CERT=/etc/ssl/tls.crt
      - TLS_CLIENT_KEY=/etc/ssl/tls.key
      - GRAPH_DB=neo4j
      - GRAPH_USER=neo4j
      - GRAPH_PASSWORD=somepassword
      - GRAPH_ENDPOINT=bolt://neo4j:7687
    volumes:
      - ./certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ./certs/client/client_cassini_key.pem:/etc/ssl/tls.key:ro
      - ./certs/client/client_cassini_certificate.pem:/etc/ssl/tls.crt:ro

  provenance-linker:
    depends_on:
      - cassini
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-linker-agent:386858fe
    networks:
      - polar
    environment:
      - BROKER_ADDR=cassini:8080
      - CASSINI_SERVER_NAME=cassini
      - TLS_CA_CERT=/etc/ssl/ca_certificate.pem
      - TLS_CLIENT_CERT=/etc/ssl/tls.crt
      - TLS_CLIENT_KEY=/etc/ssl/tls.key
      - GRAPH_DB=neo4j
      - GRAPH_USER=neo4j
      - GRAPH_PASSWORD=somepassword
      - GRAPH_ENDPOINT=neo4j://neo4j:7474
    volumes:
      - ./certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ./certs/client/client_cassini_key.pem:/etc/ssl/tls.key:ro
      - ./certs/client/client_cassini_certificate.pem:/etc/ssl/tls.crt:ro

  provenance-resolver:
    depends_on:
      - cassini
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-resolver-agent:386858fe
    networks:
      - polar
    environment:
      - BROKER_ADDR=cassini:8080
      - CASSINI_SERVER_NAME=cassini
      - TLS_CA_CERT=/etc/ssl/ca_certificate.pem
      - TLS_CLIENT_CERT=/etc/ssl/tls.crt
      - TLS_CLIENT_KEY=/etc/ssl/tls.key
      - PROXY_CA_CERT=/etc/ssl/proxy_ca.pem
      - DOCKER_CONFIG=/home/polar/.docker/
    volumes:
      - ./certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ./certs/client/client_cassini_key.pem:/etc/ssl/tls.key:ro
      - ./certs/client/client_cassini_certificate.pem:/etc/ssl/tls.crt:ro
      - ./certs/proxy_ca.pem:/etc/ssl/proxy_ca.pem:ro
      - ./config.json:/home/polar/.docker/config.json
networks:
  polar:

volumes:
  neo4j-data:
